name: llm_playground
channels:
- conda-forge
dependencies:
- python=3.11
- ipykernel=7.2.0
- jupyterlab=4.5.4
- ipywidgets=8.1.8
- matplotlib=3.10.8
- pip
- pip:
  - torch==2.10.0
  - transformers==5.1.0
  - tiktoken==0.12.0
  - ipython==9.10.0
  - huggingface_hub==1.4.1
